theme: 'jekyll-theme-minimal'

title: 'Sakura Frp'
description: '免费的内网穿透服务，轻松在自家电脑搭建网站。'

lang: 'zh-CN'

menus: 
  - 0: 
    name: 首页
    link: /
  - 1:
    name: 文档
    link: /wiki/
  - 2:
    name: 主站
    link: https://www.natfrp.com/
  # - 3: 
  #   name: 关于
  #   link: /about/
